In [1]:
%timeit 3+1

7.48 ns ± 0.03 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [4]:
def num2add(a,b):
    return a+b
%timeit num2add(3,4)

78.6 ns ± 0.666 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [8]:
a= [4+i for i in range(20)]
print(a)
%timeit a

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
22.8 ns ± 0.28 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [27]:
import numpy as np
myarr1=np.arange(100000)
lst1=list(range(100000))
lst1
%time for _ in range(10):myarr=myarr1*2
    
%time for _ in range(10):lst1=[x*2 for x in lst1]
    

CPU times: user 3.09 ms, sys: 0 ns, total: 3.09 ms
Wall time: 2.55 ms
CPU times: user 60.7 ms, sys: 0 ns, total: 60.7 ms
Wall time: 60.5 ms


In [39]:
a=np.ones_like
print(a)

<function ones_like at 0x7fab840f7b00>


In [41]:
#slicing
arr1=np.arange(13)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr1[4:7]

array([4, 5, 6])

In [45]:
arr1[4:7]=11
arr1

array([ 0,  1,  2,  3, 11, 11, 11,  7,  8,  9, 10, 11, 12])

In [50]:
nw=arr1[4:7]

In [53]:
nw[1]=10101
print(nw)
print(arr1)

[   11 10101    11]
[    0     1     2     3    11 10101    11     7     8     9    10    11
    12]


In [54]:
nw[:]=33
arr1

array([ 0,  1,  2,  3, 33, 33, 33,  7,  8,  9, 10, 11, 12])

In [55]:
ary=np.array([[1,2,3],[4,5,6],[7,8,9]])
ary[2,1]

8

In [75]:
dd=np.arange(27)
dd.reshape(3,3,3)


In [78]:
nwvlue=dd[1,0].copy
dd[1,0]=41
dd

IndexError: too many indices for array