In [7]:
import numpy as np
import sys
import time


s=range(1000)
print('the size of memory occupied by list:',sys.getsizeof(3)*len(s))

f=np.arange(1000) 
print('the size of memory occupied by numpy:',f.size*f.itemsize)


the size of memory occupied by list: 28000
the size of memory occupied by numpy: 8000


In [1]:
size=1000000

l1=range(size)
l2=range(size)
start= time.time()
result=[(x,y) for x,y in zip(l1,l2)]  
print((time.time()-start)*1000)

d1=np.arange(size)
d2=np.arange(size)
start=time.time()
result=d1+d2
print((time.time()-start)*1000)


NameError: name 'time' is not defined

In [2]:
%timeit 3+1

7.56 ns ± 0.17 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [3]:
def num2add(a,b):
    return a+b
%timeit num2add(3,4)

78.5 ns ± 1.04 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [4]:
a= [4+i for i in range(20)]
print(a)
%timeit a

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
20.8 ns ± 0.398 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [5]:
import numpy as np
myarr1=np.arange(100000)
lst1=list(range(100000))
lst1
%time for _ in range(10):myarr=myarr1*2
    
%time for _ in range(10):lst1=[x*2 for x in lst1]
    

CPU times: user 2.13 ms, sys: 10 µs, total: 2.14 ms
Wall time: 2.15 ms
CPU times: user 58.8 ms, sys: 0 ns, total: 58.8 ms
Wall time: 58.7 ms


In [6]:
a=np.ones_like
print(a)

<function ones_like at 0x7fccf004eb00>


In [7]:
#slicing
arr1=np.arange(13)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
arr1[4:7]

array([4, 5, 6])

In [9]:
arr1[4:7]=11
arr1

array([ 0,  1,  2,  3, 11, 11, 11,  7,  8,  9, 10, 11, 12])

In [10]:
nw=arr1[4:7]

In [11]:
nw[1]=10101
print(nw)
print(arr1)

[   11 10101    11]
[    0     1     2     3    11 10101    11     7     8     9    10    11
    12]


In [12]:
nw[:]=33
arr1

array([ 0,  1,  2,  3, 33, 33, 33,  7,  8,  9, 10, 11, 12])

In [13]:
ary=np.array([[1,2,3],[4,5,6],[7,8,9]])
ary[2,1]

8

In [14]:
dd=np.arange(27)
dd.reshape(3,3,3)


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
nwvlue=dd[1,0].copy
dd[1,0]=41
dd

IndexError: too many indices for array

In [21]:
name=np.array(['ali','khan','sher','rafi','rehan'])
data= np.random.randn(5,2)

In [22]:
name
data

array([[-1.43372164,  0.92459205],
       [-1.36710716, -0.96406254],
       [-0.02473073, -1.2025154 ],
       [-1.05493804,  0.32304422],
       [-0.94071146, -1.43410464]])

In [23]:
name=='khan'

array([False,  True, False, False, False])

In [24]:
data[name=='sher']

array([[-0.02473073, -1.2025154 ]])

In [28]:
print(data[2:3,0:2])

[[-0.02473073 -1.2025154 ]]


In [39]:

print(data[name=='khan' ,1])


[-0.96406254]


In [42]:
data[~(name=='khan')]

array([[-1.43372164,  0.92459205],
       [-0.02473073, -1.2025154 ],
       [-1.05493804,  0.32304422],
       [-0.94071146, -1.43410464]])