### Task Lists

- [x] <font color='red'>Broadcasting
- [x] Tensor dot
- [x] Tensor reshaping
- [x] Geometric interpretation of tensor operations
- [x] A geometric interpretation of deep learning
- [x] The engine of neural networks: gradient-based optimization
- [x] What’s a derivative?
- [x] Derivative of a tensor operation: the gradient
- [x] Stochastic gradient descent
- [x] Chaining derivatives: the Backpropagation algorithm<font/>

# WX + B

1. <font color='green'> W.T(generate matrix with tranpose size of X matrix 
2. Dot_product(X,WT)
3. After dot product add bias (b)
4. At the end apply activation_function on each element e. sigmoid , relu softmax atc
5. finally prdict value of Y_predict
6. Calculte loss (Y-Y_predict)
7. Update +W (-W),-W(+W) and b value. Backward propagation  </font>

# relu(dot(W,input)+b)

In [24]:
import numpy as np
X=np.arange(24).reshape(6,4) #input
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [26]:
#step 1 taking transpose
w=np.random.randn(*X.shape)# Randomly generate weight
w=w.T # transpose, changing rows into colums or viceversa
w

array([[ 0.43087562, -0.06590718,  0.39735761,  0.4056621 , -1.20784572,
        -0.60734431],
       [ 0.02065321, -0.73044686, -0.69281868,  0.79738992,  0.75192604,
        -0.07942189],
       [ 0.49686703,  1.03188776, -0.01075025, -0.07676662, -0.60851492,
         2.57461277],
       [ 0.45637699,  0.15453701,  0.54041264,  0.5135275 ,  0.19218883,
        -0.00337617]])

In [27]:
#step 2 dot product of (input,w,T)
dot_p=np.dot(w,X)
dot_p

array([[-23.68924028, -24.33644215, -24.98364402, -25.63084589],
       [ 11.54672104,  11.61400278,  11.68128451,  11.74856625],
       [ 44.87636634,  48.28370212,  51.6910379 ,  55.09837368],
       [ 14.11127704,  15.96494384,  17.81861064,  19.67227744]])

In [28]:
# step 3 After dot product add bias (b)
b=np.random.random(1)
step_3=dot_p + b
step_3

array([[-22.81130787, -23.45850974, -24.1057116 , -24.75291347],
       [ 12.42465345,  12.49193519,  12.55921693,  12.62649866],
       [ 45.75429875,  49.16163453,  52.56897032,  55.9763061 ],
       [ 14.98920945,  16.84287625,  18.69654306,  20.55020986]])

In [29]:
#step 4 applying relu function step 3 
#the whole proces from step_1 to step_4 is called F.p
np.maximum(step_3,0)#relu function

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [12.42465345, 12.49193519, 12.55921693, 12.62649866],
       [45.75429875, 49.16163453, 52.56897032, 55.9763061 ],
       [14.98920945, 16.84287625, 18.69654306, 20.55020986]])

- [ ] W and b are called weights or trainable perameters
- [ ] initially these weight matrics are vary small random values ( a step is called random initializtion ) 


In [30]:
#if i cahnge x it wil cause change in y
epsilon_x=0.3
def f(x , epsilon_x):
    return x+epsilon_x
x=2
y=f(x ,epsilon_x)
print(x + epsilon_x,y)

2.3 2.3


In [33]:
#Derivative of tensor operation \; the gradient
# A gradient is the derivative of a tensor opration.
#constants (x,y_pred) and w varies
y_pred=dot(w,X)
loss_value=loss(y_pred,y)
loss_value=f(w)


In [34]:
#chain rule
def a(x):
    return x +2
a(a(a(a(2))))

10

- [ ] calculate loss during culculating loss the value of w and b are randomly generated.
- [ ] Now we update the weights or value of w and b in opposite to w and b
- [ ] 

In [35]:
g =2 # is gradient
step=0.2 # step size 
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [36]:
# updatindg weigts
w1=w - step * g
w1

array([[ 0.03087562, -0.46590718, -0.00264239,  0.0056621 , -1.60784572,
        -1.00734431],
       [-0.37934679, -1.13044686, -1.09281868,  0.39738992,  0.35192604,
        -0.47942189],
       [ 0.09686703,  0.63188776, -0.41075025, -0.47676662, -1.00851492,
         2.17461277],
       [ 0.05637699, -0.24546299,  0.14041264,  0.1135275 , -0.20781117,
        -0.40337617]])

# stochastic gradient dencent
- stochastic means random 

- [x] draw a batch of training sample x and corresponding targets y
- [x] run the network on x to obtain y_pred
- [x] compute the loss of the network on the batch, a measure of the mismactch between y_pred and y
- [x] compute gradient decent of the loss with regard to network's perameters (a backward pass)
- [x] move perameters a little in the opposite direction from the gradient for example w-=step*gradient


### Naive Bayes Algorithm
- [x] it is powerful algorithum for predictive analysis
- [x] it comprises two parts 
 - Naive and BIAS
 - P(H/E)=P(E/H).P(H)/P(E)
- [x] Calulating face of in card using bias threorem example
 - p(king)= 4/52 which is 1/13
 - p(king / face)=p(face / king).p(king) / p(face)
 - p(king) =1  
 - p(face) =12 / 52 ==> 3 / 13 
 - 1(1 / 13)/(3 / 13) ==>1 / 3
 -