# <font color='red'>Numpy</font>


In [2]:
import numpy as np

In [15]:
#Create a null vector of size 10 and 10*10
a=np.zeros(10)
print('a',a)
b=np.zeros((10,10))
print('b',b)

a [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
b [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
#. How to find the memory size of any array
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [18]:
# Create a null vector of size 10 but the fifth value which is 1 
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [22]:
#Reverse a vector (first element becomes last)
a=np.arange(18).reshape(3,6)
a=a[::-1]
a

array([[12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [25]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
ab=np.nonzero([1,2,0,0,4,0])
print(ab)

(array([0, 1, 4]),)


In [17]:
#Create a 3x3 identity matrix
import numpy as np
a=np.eye(9)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
#Create a 10x10 array with random values and find the minimum and maximum values
d=np.random.randn(10,10)
dmin,dmax=d.min(),d.max()
print(dmin,dmax)

-2.4655454643797223 2.477092400323771


In [19]:
# Create a random vector of size 30 and find the mean value
a=np.random.randn(30)
a.mean()

0.012106601390957619

In [20]:
# Create a 2d array with 1 on the border and 0 inside
q=np.ones(16).reshape(4,4)
q[1:-1,1:-1]=0
q

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [22]:
#How to add a border (filled with 0's) around an existing array? 
Z=np.ones((6,6))
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [23]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [25]:
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [26]:
a=np.arange(36).reshape(6,6)
a[4:,4:]=0
a


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27,  0,  0],
       [30, 31, 32, 33,  0,  0]])

In [27]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
z = np.diag (1+np.arange(4),k=-2)
z

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0]])

In [28]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
a=np.ones((8,8))
a[1::2,::2]=0
a[::2,1::2]=0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [29]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
d=(np.unravel_index(99,(6,7,9)))
d

(1, 4, 0)

In [30]:
#Create a checkerboard 8x8 matrix using the tile function
d=np.tile(np.array([[0,1],[1,0]]),(4,4))
d

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [31]:
# Normalize a 5x5 random matrix
a=np.arange(25).reshape(5,5)
a=(a-np.mean(a))/(np.std(a))
a

array([[-1.66410059, -1.52542554, -1.38675049, -1.24807544, -1.10940039],
       [-0.97072534, -0.83205029, -0.69337525, -0.5547002 , -0.41602515],
       [-0.2773501 , -0.13867505,  0.        ,  0.13867505,  0.2773501 ],
       [ 0.41602515,  0.5547002 ,  0.69337525,  0.83205029,  0.97072534],
       [ 1.10940039,  1.24807544,  1.38675049,  1.52542554,  1.66410059]])

In [32]:
#Multiply a 5x3 matrix by a 3x2 matrix
x=np.arange(15).reshape(5,3)
y=np.arange(6).reshape(3,2)
z=x@y
z

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [33]:
 #Given a 1D array, negate all elements which are between 3 and 8, in place
a=np.arange(12)
a[(a>3)&(a<8)]*=-1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

In [34]:
#What is the output of the following script
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [35]:
#What are the result of the following expressions?
#np.array(0) / np.array(0)
#np.array(0) // np.array(0)
#np.array([np.nan]).astype(int).astype(float)

In [36]:
#How to round away from zero a float array ?
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[  2. -10.   1.  -5.   6.  10. -10.   6.  10.  -8.]


In [37]:
print(np.where(Z>0,np.ceil(Z),np.floor(Z)))

[  2. -10.   1.  -5.   6.  10. -10.   6.  10.  -8.]


In [38]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 3 7 8]


In [39]:
#Is the following expressions true? 
np.sqrt(-1)==np.emath.sqrt(-1)

/home/zulkifel/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [41]:
# How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today') - np.timedelta64(3)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)

2020-07-14


In [42]:
#How to get all the dates corresponding to the month of July 2019?
dt=np.arange('2019-07','2019-08', dtype='datetime64[D]')
dt

array(['2019-07-01', '2019-07-02', '2019-07-03', '2019-07-04',
       '2019-07-05', '2019-07-06', '2019-07-07', '2019-07-08',
       '2019-07-09', '2019-07-10', '2019-07-11', '2019-07-12',
       '2019-07-13', '2019-07-14', '2019-07-15', '2019-07-16',
       '2019-07-17', '2019-07-18', '2019-07-19', '2019-07-20',
       '2019-07-21', '2019-07-22', '2019-07-23', '2019-07-24',
       '2019-07-25', '2019-07-26', '2019-07-27', '2019-07-28',
       '2019-07-29', '2019-07-30', '2019-07-31'], dtype='datetime64[D]')

In [43]:
#How to compute ((A+B)*(-A/2)) in place (without copy)? 
a=np.ones(3)*1
b=np.ones(3)*2
c=np.ones(3)*3
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)


array([-1.5, -1.5, -1.5])

In [44]:
#Extract the integer part of a random array of positive numbers using 4 different methods
a=np.random.uniform(-10,10,+10)
a=(a-a%1)
a=(a//1)
a=np.floor(a)
a=np.trunc(a)
a=a.astype(int)


In [45]:
def gen():
    for x in range(10):
        yield x
y=np.fromiter(gen(),dtype=int,count=-1)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
#Create a vector of size 10 with values ranging from 0 to 1, both excluded
x=np.linspace(0,1,11,endpoint=False)[1:]
#Z = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [47]:
#How to sum a small array faster than np.sum?
z=np.arange(10)
z=np.add.reduce(z)
z


45

In [48]:

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
z=np.array_equal(A,B)
z

False


False

In [49]:
#making array immutalbe
Z = np.zeros(10)
Z.flags.writeable = False
#Z[0] = 1


In [54]:
#Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinate
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.11167352 0.52084276 0.78299352 0.70626717 0.6583872  0.72295386
 0.68205664 0.84377825 0.37927951 0.78978594]
[0.87326165 0.23743172 0.4991244  1.12364241 0.32279329 1.38455085
 1.55562403 1.01725897 1.05138472 1.17100063]


In [55]:
d=np.arange(100).astype(np.float32)
f=d.view(np.int32)
f[:]=d
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int32)

In [56]:
#How to tell if a given 2D array has null columns? 
Z = np.random.randint(0,3,(3,10))
#print((~Z.any(axis=0)).any())
print(~Z.any())

False


In [57]:
#find nearest value in a given array

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4008243915798908


In [60]:
#How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [61]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [68]:
x=np.arange(12).reshape(6,2)
x.argmin()
x.argmax()

11

In [69]:
argmin?