# Numpy Basics

In [1]:
import numpy as np

In [3]:
a_1d=np.array([1,2,3,4]) # id array
a_1d
type(a_1d)# tels type 
a_1d.ndim#tels dimension
a_1d.size # tels size of array it contain 4 elements
a_1d.shape

(4,)

In [ ]:
b_2d=np.array([[1,2,3],[14,5,6]]) #2d array
b_2d
#b.ndim
b_2d.size# it contains 6 elements
b_2d.shape# returns tupple (row,colum)
b_2d.dtype# it tels data type our array contain


In [4]:
aad=np.array([[1,0,0,1],[0,0,0,0],[0,0,0,0],[1,0,0,1]])
aad

array([[1, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 1]])

In [9]:
# we can create matrix of 1 and 0 
ones_1=np.ones(5)
print("ones:",ones_1)
zeros_0=np.zeros(3)
print("zeros:",zeros_0)

ones: [1. 1. 1. 1. 1.]
zeros: [0. 0. 0.]


In [12]:
mx=np.ones((5,6))
mx

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
mx_z=np.zeros((3,5))
mx_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
#for generating int data
ones_a=np.ones((2,3),dtype='int')
ones_a

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
#changing data type
mx=np.ones((5,6),dtype=bool)
mx

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [16]:
#changing data type
mx=np.ones((5,6),dtype=str)
mx

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

In [15]:
#changing data type
mx_z=np.zeros((3,5),dtype=bool)
mx_z

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [17]:
#changing data type
mx_z=np.zeros((3,5),dtype=str)
mx_z

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [18]:
#creating empty matrix
em_mx=np.empty((3,3))
em_mx

array([[4.65014864e-310, 4.65014881e-310, 0.00000000e+000],
       [0.00000000e+000, 4.65014864e-310, 4.65014878e-310],
       [0.00000000e+000, 0.00000000e+000, 4.65014865e-310]])

# numpy Function

In [48]:
#arange
#np.array(start,end,steps)
rg_1d=np.arange(1,13,1)
rg_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [79]:
#linespace
np.linspace(1,5,)


array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [54]:
#reshaping
rg_2d=rg_1d.reshape(4,3)
rg_2d


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
rg_3d=rg_1d.reshape(1,6,2)
rg_3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [83]:
ar_2d=np.arange(1,11).reshape(2,5)
ar_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [84]:
#ravel() it convert multidimensional array into 1-d
ar_2d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
#flaten it also convert mul-dims into 1-d
ar_2d.flatten('F')# fortan
print("another")
ar_2d.flatten('C')# C

another


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
#transpose
ar_2d.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

# Mathematics operation using Numpy

In [107]:
x=np.arange(1,10).reshape(3,3)
y=np.arange(1,10).reshape(3,3)
print(x)
print(y)
#x+y
np.add(x,y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [125]:
print(x)
#x*y
#np.multiply(x,y) for element vise multiplication
#for matrix product we use @
x@y

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [110]:
#also
x.dot(y)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [106]:
#x/y
np.divide(x,y)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [111]:
#for maximum value in a matrix
x.max()

9

In [112]:
y.min()

1

In [113]:
x.argmax()

8

In [114]:
y.argmin()

0

In [118]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
#we can find max and min value of row and matrix
x.max(axis=0)#for colum

array([3, 6, 9])

In [117]:
x.max(axis=1)#for row

array([3, 6, 9])

In [119]:
x.min(axis=0)#colum

array([1, 2, 3])

In [120]:
x.min(axis=1)#row

array([1, 4, 7])

In [121]:
#for sum of a matrix
np.sum(x)

45

In [122]:
np.sum(x,axis=0)#it add all each

array([12, 15, 18])

In [123]:
np.sum(x,axis=1)

array([ 6, 15, 24])

In [127]:
#for average of a matrix
np.mean(x)

5.0

In [132]:
#for sqr
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [133]:
#standard division
np.std(x)

2.581988897471611

In [134]:
#for eponent
np.exp(x)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [135]:
#for natural log
np.log(x)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [137]:
#for log base 10
np.log10(x)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

# Numpy array slicing(:)

In [141]:
nas=np.arange(1,101).reshape(10,10)
nas

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [146]:
#for row 3 forth element
nas[3,4]

35

In [148]:
nas[3,4].ndim

0

In [149]:
#for single row
nas[3]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [150]:
#for single colum
nas[:,2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [159]:
nas[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [158]:
nas[:,0:1]# for 2d

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [167]:
nas

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])