In [1]:
import numpy as np
l=list(range(10))
[str(c) for c in l]


['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [3]:
[type (item) for item in l]

[int, int, int, int, int, int, int, int, int, int]

In [3]:
np.zeros(10,dtype='int')

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((4,4),dtype='float')


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.full((3,3),'s')

array([['s', 's', 's'],
       ['s', 's', 's'],
       ['s', 's', 's']], dtype='<U1')

In [4]:
np.arange(0,8,2)

array([0, 2, 4, 6])

In [5]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
np.random.normal(0,1,(3,3))

array([[ 0.32828602,  0.49863061,  0.21800154],
       [-0.55091325,  0.95355418, -0.02648606],
       [ 0.80066705,  0.45842494,  1.18753832]])

In [7]:
#create an identity matrix
np.eye(3,3,2)


array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.kron(np.eye(2), np.ones((2,2)))

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [18]:
#set a rondom seed
np.random.seed(0)
a1=np.random.randint(6, size=3)
a2=np.random.randint(6,size=(3,2))

#a3=np.random.randint(6,size=(3,3,3))
#print('dimension',a3.ndim,'size',a3.size,'shape',a3.shape,)

array([4, 5, 0])

In [10]:
data_1=[1,2,3,4,5]
np.asarray(data_1)

array([1, 2, 3, 4, 5])

In [14]:
np.ones_like(data_1)

array([1, 1, 1, 1, 1])

In [15]:
np.zeros_like(data_1)

array([0, 0, 0, 0, 0])

In [21]:
a=np.full((2,2),'d')

np.full_like((a),'f')

array([['f', 'f'],
       ['f', 'f']], dtype='<U1')

In [22]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.empty(8,dtype='u4')

array([         0, 1072693248,          0, 1072693248,          0,
       1072693248,          0, 1072693248], dtype=uint32)

In [24]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2,2]

9

In [25]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('array 0 :==>',arr3d[0])
print('array 1 :==>',arr3d[1])                

array 0 :==> [[1 2 3]
 [4 5 6]]
array 1 :==> [[ 7  8  9]
 [10 11 12]]


In [26]:
arr3d[1,1:2]

array([[10, 11, 12]])

In [27]:
arr3d[:2,1]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [28]:
arr3d[0:3,:1]

array([[[1, 2, 3]],

       [[7, 8, 9]]])

In [29]:
ar2d=np.random.randn(9).reshape(3,3)
ar2d

array([[-1.51698273, -0.86627621, -0.05503512],
       [-0.10731045,  1.36546718, -0.09769572],
       [-2.42595457, -0.4530558 , -0.470771  ]])

In [30]:
print(ar2d[1:6])
print("------------")
print(ar2d[:2])
print("------------")
print(ar2d[0:1,1:2])

[[-0.10731045  1.36546718 -0.09769572]
 [-2.42595457 -0.4530558  -0.470771  ]]
------------
[[-1.51698273 -0.86627621 -0.05503512]
 [-0.10731045  1.36546718 -0.09769572]]
------------
[[-0.86627621]]


In [97]:
d=np.zeros((6,6))# dtype='int')
d[1:5,1:5]=1

print(d)
print("-----------")
d[1:2,:2]=3
print(d)
d[1:2,:2]

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
-----------
[[0. 0. 0. 0. 0. 0.]
 [3. 3. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


array([[3., 3.]])

In [123]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data=np.random.randn(7,7)
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1.11637454 -0.2509793  -0.41522808 -0.63908615  2.49776759 -3.00512816
  -0.87399723]
 [-2.65018924  1.12400545 -0.21363701  1.13183157  0.03723304  1.30275033
   0.24990045]
 [-0.64586771  0.47119601 -0.39810329 -0.95921519  0.54087305 -0.07824546
   1.83379274]
 [ 1.0246933  -0.08166743 -2.62754439 -0.35645775 -0.09860287 -1.3003954
   0.28873961]
 [ 1.45137755 -0.17791818 -0.16990685  0.55012716  2.09628076 -0.87680291
  -0.43299184]
 [-0.84589888  0.16373274  0.29839875  0.23766958 -0.15580481 -0.8595119
   2.5290124 ]
 [-0.84448494  0.89066205  0.77200376  0.02031364 -1.58325014  0.07544465
   0.5921135 ]]


In [124]:
print (names=='Bob')
data[names=='Bob']

[ True False False  True False False False]


array([[ 1.11637454, -0.2509793 , -0.41522808, -0.63908615,  2.49776759,
        -3.00512816, -0.87399723],
       [ 1.0246933 , -0.08166743, -2.62754439, -0.35645775, -0.09860287,
        -1.3003954 ,  0.28873961]])