# Pandas:
    it is used for machien learning, Deeplearning ,for data science, data handling, data organizing and data analysis  . 

In [2]:
import pandas as pd
obj=pd.Series([1,2,-5,-7,0.5,3])
print(obj)# pandas returns valuse and index

0    1.0
1    2.0
2   -5.0
3   -7.0
4    0.5
5    3.0
dtype: float64


In [3]:
#for values and index
sales=pd.Series([100,200,3,300,400])
print(sales.values)
print(sales.index)

[100 200   3 300 400]
RangeIndex(start=0, stop=5, step=1)


In [4]:
#we can change index
sales=pd.Series([12,1,2,3,4],index=['a','b','c','d','e'])
print(sales)
print(sales.values)
print(sales.index)

a    12
b     1
c     2
d     3
e     4
dtype: int64
[12  1  2  3  4]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


In [5]:
sales=pd.Series([12,1,2,3,4],index=['jan','feb','marc','aprl','may'],name='4 moth sales')
print(sales)

jan     12
feb      1
marc     2
aprl     3
may      4
Name: 4 moth sales, dtype: int64


In [6]:
#canteen sales
brgr=pd.Series([10,13,12,15,16,44,0],index=['mon','tues','wed','thr','fri','sta','sun'])
print(brgr)
print(brgr['wed'])#for acessing data
#print(brgr[2])

mon     10
tues    13
wed     12
thr     15
fri     16
sta     44
sun      0
dtype: int64
12


In [7]:
#for multipple data
print(brgr[[2,4,6]])
print(brgr [['tues','fri']])

wed    12
fri    16
sun     0
dtype: int64
tues    13
fri     16
dtype: int64


In [8]:
#we can select data conditionaly
print(brgr>12)#method 1
print(brgr[brgr>12])

mon     False
tues     True
wed     False
thr      True
fri      True
sta      True
sun     False
dtype: bool
tues    13
thr     15
fri     16
sta     44
dtype: int64


In [9]:
brgr=brgr*3
print(brgr)

mon      30
tues     39
wed      36
thr      45
fri      48
sta     132
sun       0
dtype: int64


In [10]:
brgr=brgr/3

In [11]:
brgr

mon     10.0
tues    13.0
wed     12.0
thr     15.0
fri     16.0
sta     44.0
sun      0.0
dtype: float64

In [12]:
#checking wether a series existing or not we just type name of a series
'wed' in brgr
'pet' in brgr


False

In [13]:
#from numpy to pandas
import numpy as np
dta=np.array([12,34,55,66,777,88,12])
ind=np.array(['a','b','c','d','e','f','g'])
obj1=pd.Series(dta,index=ind)
obj1


a     12
b     34
c     55
d     66
e    777
f     88
g     12
dtype: int64

In [15]:
'a' in obj1

True

In [16]:
#from dictionary to pandas series
home_tax={'ali':1222,
         'sher':222,
         'khan':123,
         'ahmad':444,
         'gull':555}
tax_paid=pd.Series(home_tax)
print(tax_paid)
tax_paid.index

ali      1222
sher      222
khan      123
ahmad     444
gull      555
dtype: int64


Index(['ali', 'sher', 'khan', 'ahmad', 'gull'], dtype='object')

In [17]:
#if we change the index position the values remains same
tax_paid=pd.Series(home_tax,index=['ahmad','gull','khan','sher','ali',])
tax_paid

ahmad     444
gull      555
khan      123
sher      222
ali      1222
dtype: int64

In [18]:
#for identifying null value, NaN shows the null value
tax_paid=pd.Series(home_tax,index=['ahmad','gull','khan','sher','ali','mir'])
tax_paid
pd.isnull(tax_paid)


ahmad    False
gull     False
khan     False
sher     False
ali      False
mir       True
dtype: bool

In [19]:
tax_paid.name="tax paid by homes of a village"
tax_paid.index.name="home owner name"
print (tax_paid)
print(tax_paid.index)

home owner name
ahmad     444.0
gull      555.0
khan      123.0
sher      222.0
ali      1222.0
mir         NaN
Name: tax paid by homes of a village, dtype: float64
Index(['ahmad', 'gull', 'khan', 'sher', 'ali', 'mir'], dtype='object', name='home owner name')


In [25]:
arr4=np.random.randn(6,3)
print(arr4)
print('------')
np.dot(arr4.T,arr4)

[[ 1.26924729  0.82145231 -0.65653703]
 [-0.28569201 -0.68133866  1.01112549]
 [ 0.64570037  1.65191983  0.98824684]
 [ 0.27107373 -0.32934182  0.29440374]
 [-0.43494823  1.28719108  0.91836204]
 [ 0.81921418  0.10232279  0.48940553]]
------


array([[ 3.04331036,  1.73861125, -0.40277384],
       [ 1.73861125,  5.64364227,  1.53949711],
       [-0.40277384,  1.53949711,  3.59962763]])

In [10]:
import numpy as np
ar4=np.arange(12).reshape(2,3,2)
ar4
#ar4.transpose((1,4,0))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [6]:
import pandas as pd
import numpy as np
data1=pd.read_csv("examples/sample.csv")
data1

studentid        name    physics    chemistry    biology    mathematics
0       a11    ali khan        1221         2232       1423          2343
1       a12    sher jan        3342         6654       7453          4453
2       a121      wasim       11121          342       5643          4536

In [8]:
data1=pd.read_csv("examples/sample.csv",names=['id','Name','phy','chem','bio','math'])
data1

id        Name        phy         chem        bio          math
0  studentid        name    physics    chemistry    biology    mathematics
1        a11    ali khan       1221         2232       1423           2343
2        a12    sher jan       3342         6654       7453           4453
3        a121      wasim       11121         342       5643          4536

In [13]:
data1=pd.read_csv("examples/sample.csv",skiprows=1,
                  names=['id','Name','phy','chem','bio','math'])#we can skip rows by skiprows method
data1

id        Name    phy  chem   bio  math
0  a11    ali khan    1221  2232  1423  2343
1  a12    sher jan    3342  6654  7453  4453
2  a121      wasim   11121   342  5643  4536

In [14]:
data2=pd.read_csv("examples/sample2.csv")
data2

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [20]:
data2=pd.read_csv("examples/sample2.csv",index_col="message",)
data2

a   b   c   d
message               
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [21]:
data3=pd.read_csv("examples/sample3.csv",)
data3

key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [24]:
data3=pd.read_csv("examples/sample3.csv",index_col=["key1"])
data3

key2  value1  value2
key1                     
one     a       1       2
one     b       3       4
one     c       5       6
one     d       7       8
two     a       9      10
two     b      11      12
two     c      13      14
two     d      15      16

In [30]:
data3=pd.read_csv("examples/sample3.csv",index_col=["key1", "key2"])
data3

value1  value2
key1 key2                
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In some cases, a table might not have a fixed delimiter

In [45]:
data4=pd.read_table("examples/sample4.txt",sep="\s+")
data4

A         B              C
'aaa -0.264438 -1.026059  -0.619500\n',
'bbb  0.927272  0.302904  -0.032399\n',
'ccc -0.264273 -0.386314  -0.217601\n',
'ddd -0.871858 -0.348382    1.100491\n'

## Handling missing values

In [46]:
data5=pd.read_csv("examples/sample5.csv",)
data5

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [47]:
pd.isnull(data5)

something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [51]:
data5=pd.read_csv("examples/sample5.csv",na_values=["NULL"])
data5

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [52]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
data5=pd.read_csv("examples/sample5.csv",na_values=sentinels)
data5

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [3]:
data_6=pd.read_csv("./train.csv",nrows=10)
data_6

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [13]:
data_6['Sex']


0      male
1    female
2    female
3    female
4      male
5      male
6      male
7      male
8    female
9    female
Name: Sex, dtype: object

In [20]:
data_6.Sex.value_counts()

female    5
male      5
Name: Sex, dtype: int64