# Pandas:
    it is used for machien learning, Deeplearning ,for data science, data handling, data organizing and data analysis  . 

In [2]:
import pandas as pd
obj=pd.Series([1,2,-5,-7,0.5,3])
print(obj)# pandas returns valuse and index

0    1.0
1    2.0
2   -5.0
3   -7.0
4    0.5
5    3.0
dtype: float64


In [3]:
#for values and index
sales=pd.Series([100,200,3,300,400])
print(sales.values)
print(sales.index)

[100 200   3 300 400]
RangeIndex(start=0, stop=5, step=1)


In [4]:
#we can change index
sales=pd.Series([12,1,2,3,4],index=['a','b','c','d','e'])
print(sales)
print(sales.values)
print(sales.index)

a    12
b     1
c     2
d     3
e     4
dtype: int64
[12  1  2  3  4]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


In [5]:
sales=pd.Series([12,1,2,3,4],index=['jan','feb','marc','aprl','may'],name='4 moth sales')
print(sales)

jan     12
feb      1
marc     2
aprl     3
may      4
Name: 4 moth sales, dtype: int64


In [6]:
#canteen sales
brgr=pd.Series([10,13,12,15,16,44,0],index=['mon','tues','wed','thr','fri','sta','sun'])
print(brgr)
print(brgr['wed'])#for acessing data
#print(brgr[2])

mon     10
tues    13
wed     12
thr     15
fri     16
sta     44
sun      0
dtype: int64
12


In [7]:
#for multipple data
print(brgr[[2,4,6]])
print(brgr [['tues','fri']])

wed    12
fri    16
sun     0
dtype: int64
tues    13
fri     16
dtype: int64


In [8]:
#we can select data conditionaly
print(brgr>12)#method 1
print(brgr[brgr>12])

mon     False
tues     True
wed     False
thr      True
fri      True
sta      True
sun     False
dtype: bool
tues    13
thr     15
fri     16
sta     44
dtype: int64


In [9]:
brgr=brgr*3
print(brgr)

mon      30
tues     39
wed      36
thr      45
fri      48
sta     132
sun       0
dtype: int64


In [10]:
brgr=brgr/3

In [11]:
brgr

mon     10.0
tues    13.0
wed     12.0
thr     15.0
fri     16.0
sta     44.0
sun      0.0
dtype: float64

In [12]:
#checking wether a series existing or not we just type name of a series
'wed' in brgr
'pet' in brgr


False

In [13]:
#from numpy to pandas
import numpy as np
dta=np.array([12,34,55,66,777,88,12])
ind=np.array(['a','b','c','d','e','f','g'])
obj1=pd.Series(dta,index=ind)
obj1


a     12
b     34
c     55
d     66
e    777
f     88
g     12
dtype: int64

In [15]:
'a' in obj1

True

In [16]:
#from dictionary to pandas series
home_tax={'ali':1222,
         'sher':222,
         'khan':123,
         'ahmad':444,
         'gull':555}
tax_paid=pd.Series(home_tax)
print(tax_paid)
tax_paid.index

ali      1222
sher      222
khan      123
ahmad     444
gull      555
dtype: int64


Index(['ali', 'sher', 'khan', 'ahmad', 'gull'], dtype='object')

In [17]:
#if we change the index position the values remains same
tax_paid=pd.Series(home_tax,index=['ahmad','gull','khan','sher','ali',])
tax_paid

ahmad     444
gull      555
khan      123
sher      222
ali      1222
dtype: int64

In [18]:
#for identifying null value, NaN shows the null value
tax_paid=pd.Series(home_tax,index=['ahmad','gull','khan','sher','ali','mir'])
tax_paid
pd.isnull(tax_paid)


ahmad    False
gull     False
khan     False
sher     False
ali      False
mir       True
dtype: bool

In [19]:
tax_paid.name="tax paid by homes of a village"
tax_paid.index.name="home owner name"
print (tax_paid)
print(tax_paid.index)

home owner name
ahmad     444.0
gull      555.0
khan      123.0
sher      222.0
ali      1222.0
mir         NaN
Name: tax paid by homes of a village, dtype: float64
Index(['ahmad', 'gull', 'khan', 'sher', 'ali', 'mir'], dtype='object', name='home owner name')


In [25]:
arr4=np.random.randn(6,3)
print(arr4)
print('------')
np.dot(arr4.T,arr4)

[[ 1.26924729  0.82145231 -0.65653703]
 [-0.28569201 -0.68133866  1.01112549]
 [ 0.64570037  1.65191983  0.98824684]
 [ 0.27107373 -0.32934182  0.29440374]
 [-0.43494823  1.28719108  0.91836204]
 [ 0.81921418  0.10232279  0.48940553]]
------


array([[ 3.04331036,  1.73861125, -0.40277384],
       [ 1.73861125,  5.64364227,  1.53949711],
       [-0.40277384,  1.53949711,  3.59962763]])

In [35]:
ar4=np.arange(12).reshape(2,3,2)
ar4
#ar4.transpose((1,4,0))

AxisError: axis 4 is out of bounds for array of dimension 3